### ISSUE TITLE
Elasticsearch not working

### ISSUE THREAD

**Issue by sticky99** [bsmithio/OPNsense-Dashboard#51]
Lost a HD, so had to reinstall this from scratch. All is working except elasticsearch. I first noticed this when adding elasticsearch as a data source, it produced the error

`Elasticsearch error: Bad Gateway`

I tried to connect to the URL via a browser on port 9200 without success. Looking at the container the container is running

![opn1](https://github.com/bsmithio/OPNsense-Dashboard/assets/12866911/8fa4d0da-1e13-4400-a631-50df99a24b50)

but looking at netstat I don't see ports 9200 or 9300 as open

![opn2](https://github.com/bsmithio/OPNsense-Dashboard/assets/12866911/d9342235-98d9-40a7-8aa5-8ebd82235472)

when I look at the logs for the container I see plenty of info messages, but no errors

![opn3](https://github.com/bsmithio/OPNsense-Dashboard/assets/12866911/6520f4c8-b52c-4e06-a149-6378e35a4db7)

Am I missing something obvious?

**Comment by bsmithio** [comment]
Could you try this docker compose? This may be the solution.

```
version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.4
    volumes:
      - mongodb_data:/data/db
    restart: "unless-stopped"
    environment:
      # Change this to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
    networks:
      - graylog  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      # Change this to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: "unless-stopped"
    networks:
      - graylog
  graylog:
    container_name: graylog
    image: graylog/graylog:5.0.2
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      # Change these to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
      - ROOT_TIMEZONE=CST6CDT
      - GRAYLOG_TIMEZONE=CST6CDT
      # CHANGE ME (must be at least 16 characters)! This is not your password, this is meant for salting the password below.
      - GRAYLOG_PASSWORD_SECRET=ZDcwMzQ3NTE4ZTIwM
      # Username is "admin"
      # Password is "admin", change this to your own hashed password. 'echo -n "password" | sha256sum' 
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    networks:
      - graylog
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog UDP
      - 1514:1514/udp
      # Syslog TCP Optional
      #- 1514:1514
    restart: "unless-stopped"
  influxdb:
    container_name: influxdb
    image: influxdb:2.6.1
    ports:
      - '8086:8086'
    volumes:
      - influxdb2_data:/var/lib/influxdb2
    environment:
      # Change this to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
    restart: "unless-stopped"
    networks:
      - graylog
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.10
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      # Change this to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
      # Change these
      - GF_SECURITY_ADMIN_USER=opnsense
      - GF_SECURITY_ADMIN_PASSWORD=opnsense
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    restart: "unless-stopped"
    networks:
      - graylog
networks:
  graylog:
    driver: bridge
volumes:
  grafana_data:
  influxdb2_data:
  graylog_data:
  es_data:
  mongodb_data:
  ```
